name = "HostCPUFeatures"
uuid = "3e5b6fbb-0976-4d2c-9146-d79de83f2fb0"
authors = ["Chris Elrod <elrodc@gmail.com> and contributors"]
version = "0.1.7"

[deps]
BitTwiddlingConvenienceFunctions = "62783981-4cbd-42fc-bca8-16325de8dc4b"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
BitTwiddlingConvenienceFunctions = "0.1"
IfElse = "0.1"
Static = "0.2, 0.3, 0.4, 0.5, 0.6"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
